- src/es/components/organisms/footer/Footer.js
Fixed width of cta container. It now takes 100% as in the Design
> MIDUWEB-264: Adjusted cta spacings

- src/es/components/pages/ContentPage.html
chore(web-components-toolbox): update subproject commit hash
> chore(ContentPage.html): add ordered list to the content page

- index.html
- src/es/components/molecules/teaser/fullwidth-/fullwidth-.css
- src/es/components/organisms/bodySection/BodySection.js
- src/es/components/pages/ContentPage.html
- src/es/components/pages/Figure.html
- src/es/components/pages/Home.html
- src/es/components/pages/OBodySection.html
- src/es/components/pages/Teaser.html
@Weedshaker Hier das renaming der komponente von ks-o-body-style zu ks-o-body-section. Hoffe damit ist's klarer, dass die Aufgaben der Komponente nicht ganz identisch sind.
> feat: rename to body section

- src/es/components/atoms/button/variant/variant.css
- src/es/components/pages/ColorStage.html
chore(css): update subproject commit reference in web-components-toolbox-migros-design-experience
style(button/variant.css): add round style for button host with border-radius and padding properties
style(ColorStage.html): update text inside back link and add round style to favorite button
style(ColorStage.html): add round style to ks-a-button component for consistency
style(ColorStage.html): add round style to favorite button for consistency
chore(web-components-toolbox): update subproject commit reference to a026a874b
> feat(ColorStage.html): update "merken" button and back link text [MIDUWEB-110]

- src/es/components/atoms/heading/Heading.js
- src/es/components/pages/ColorStage.html
- src/es/components/pages/ContentPage.html
refactor(ColorStage.html): replace h1 tags with ks-a-heading component for consistency and styling improvements
refactor(ColorStage.html): update heading tag and color for better styling and consistency
style(ContentPage.html): replace h1 tag with custom ks-a-heading component for ContentPage title
> style(Heading.js): add CSS rules for content-stage attribute in Heading component

- src/es/components/controllers/withFacet/WithFacet.js
refactor(WithFacet.js): refactor logic to handle multiple values in entriesWithUnderscore
refactor(WithFacet.js): refactor logic to handle multiple values in children array
refactor(WithFacet.js): remove unused selectedFilter variable
> refactor(WithFacet.js): refactor logic to handle multiple values in children array

- index.html
- src/es/components/atoms/numberOfOffersButton/NumberOfOffersButton.js
- src/es/components/controllers/withFacet/WithFacet.js
- src/es/components/molecules/filterCategories/FilterCategories.js
- src/es/components/molecules/filterSelect/FilterSelect.js
- src/es/components/organisms/offersPage/OffersPage.js
- src/es/components/pages/Modal.html
refactor(WithFacet.js): remove console.log statements for initialRequest, entriesWithUnderscore, request, and response in WithFacet class
refactor(WithFacet.js): optimize setting and removing selected children in url params, handle cases where child.urlpara is null or undefined
> refactor(WithFacet.js): extended filter and url params

- src/es/components/controllers/autoComplete/AutoComplete.js
- src/es/components/controllers/autoCompleteLocation/AutoCompleteLocation.js
- src/es/components/controllers/withFacet/WithFacet.js
- src/es/components/molecules/autoCompleteList/AutoCompleteList.js
- src/es/components/organisms/offersPage/OffersPage.js
- src/es/components/pages/Angebotsliste-Suchergebnis.html
refactor(AutoComplete.js): add logic to update results when token length is less than 3
feat(AutoComplete.js): add event listener to update results when clicking on prediction and close search dialog
refactor(AutoComplete.js): simplify event listener and event dispatch method calls
refactor(AutoCompleteLocation.js): simplify event listener names for request and selection events
refactor(AutoCompleteLocation.js): remove unnecessary dispatchInputChange method
refactor(AutoCompleteLocation.js): remove unnecessary dispatchInputChange calls
feat(AutoCompleteLocation.js): add event dispatch for 'request-with-facet' with key 'location-search'
refactor(WithFacet.js): improve handling of search term and location in filterRequest
feat(WithFacet.js): add console log for debugging purposes …
> feat(OffersPage.js): improve search and location search [MIDUWEB-617]

- src/es/components/molecules/event/Event.js
- src/es/components/molecules/tile/Tile.js
- src/es/components/molecules/tileFactory/TileFactory.js
- src/es/components/pages/Event.html
- src/es/components/pages/Tile.html
refactor(Event.js): improve button rendering logic in renderHTML method
refactor(Event.js): clean up commented out code and improve readability by removing unnecessary comments and adding missing import for 'a-icon-mdx' component
refactor(Tile.js): extract button rendering logic into a separate function for better readability and maintainability
refactor(TileFactory.js): extract button creation logic into a separate function
feat(Event.html): add multiple buttons with different configurations to the Event page
chore(Tile.html): update button object to buttons array with multiple button objects
> fix(Tile.js, Event.js): introduce buttons [NO-TICKET]

- src/es/components/molecules/linkList/LinkList.js
- src/es/components/molecules/linkList/default-/default-.css
- src/es/components/molecules/linkList/readme.md
- src/es/components/molecules/logoList/LogoList.js
- src/es/components/pages/LinkList.html
added hover
added description behavior
> fixed font-size

- src/es/components/pages/ColorStage.html
style(ColorStage.html): change button style from round to include an icon instead of just being round
style(ColorStage.html): change button to include an icon in addition to color and round properties
> feat(ColorStage.html): improve favorite icon and back link [MIDUWEB-532]

- src/css/variablesCustom.css
- src/es/components/pages/Inspirationsdetail.html
style(css): update link text decoration to underline and hover text decoration to underline in variablesCustom.css
> style(css): improve links [MIDUWEB-503]

- src/es/components/pages/ColorStage.html
chore(css): update subproject commit reference in web-components-tool…box-migros-design-experience
chore(html): add link-underline class to topline paragraph in ColorStage.html
chore(components): update subproject commit reference in web-components-toolbox
> fix(ColorStage.html): improve backlink style on hover [MIDUWEB-779] 

- src/es/components/molecules/teaser/Teaser.js
- src/es/components/molecules/teaser/fullwidth-/fullwidth-.css
- src/es/components/molecules/teaser/link-box-/link-box-.css
- src/es/components/molecules/teaser/story-/story-.css
- src/es/components/molecules/teaser/tile-content-/tile-content-.css
- src/es/components/pages/Teaser.html
fix(teaser): update color variable to use mdx-color attribute if available, fallback to default color if not present
style(teaser): update background color variable in link-box-.css
style(teaser): update color variables in story-.css
style(teaser/tile-content-.css): update pretitle and background color variables to use mdx-color attribute if available
style(teaser/tile-content-.css): update pretitle hover color to use mdx-color attribute if available
style(teaser/tile-content-.css): update background color hover to use mdx-color attribute if available
feat(Teaser.html): update ks-m-teaser component to use mdx-color attribute for color styling
> fix(Teaser): add mdx-color attribute to improve color handling in cms [NO-TICKET]

- src/es/components/molecules/contactRow/ContactRow.js
- src/es/components/organisms/bodySection/BodySection.js
[Jira Ticket](https://jira.migros.net/browse/MIDUWEB-504)
> fix(BodySection.js, ContactRow.js): improve tables and contact row link style [MIDUWEB-504]

- src/es/components/pages/ColorStage.html
chore(css): update subproject commit reference for web-components-toolbox-migros-design-experience
feat(pages): add image inside simple version in ColorStage.html
feat(pages): add image as background in ColorStage.html
chore(components): update subproject commit reference for web-components-toolbox
> feat(ColorStage.html): improve image handling for SEO [MIDUWEB-816]

- index.html
- src/css/variablesCustom.css
- src/es/components/pages/Checkout-Easy-Buchungsart-Kurskonfiguration.html
chore(index.html): add new link for 'Checkout Easy Buchungsart Kurskonfiguration'
style(variablesCustom.css): add new CSS variables for form styling
feat(pages): add Checkout Easy Buchungsart Kurskonfiguration page
> feat(Checkout-Easy-Buchungsart-Kurskonfiguration.html): add easy booking type config page [MIDUWEB-738]

- src/es/components/controllers/withFacet/WithFacet.js
- src/es/components/molecules/filterCategories/FilterCategories.js
- src/es/components/molecules/filterSelect/FilterSelect.js
- src/es/components/organisms/offersPage/OffersPage.js
- src/es/components/organisms/offersPage/readme.md
- src/es/components/pages/Angebotsliste-Suchergebnis.html
feat(WithFacet.js): implement functionality to update URL parameter based on event details
feat(FilterCategories.js): add center-id attribute to mdx-checkbox component in FilterCategories
> refactor(WithFacet.js): add methods to handle adding and removing URL parameter

- src/es/components/molecules/buttons/Buttons.js
- src/es/components/molecules/tile/Tile.js
- src/es/components/organisms/tileList/TileList.js
- src/es/components/pages/Angebotsliste-Suchergebnis.html
style(Tile.js): add 'with-url-params' attribute to ks-m-buttons component
style(TileList.js): change comment delimiters from /* HTML */ to /* html */ for consistency
chore(Angebotsliste-Suchergebnis.html): update API endpoints to use development environment URLs
> refactor(Buttons.js): add support for keeping URL parameters in button links

- src/es/customer-loyality/index-wc.html
- src/es/customer-loyality/organisms/form/Form.js
- src/es/customer-loyality/pages/Voting.js
- checkbox view update
- typos
- real endpoint
> fix(customer-loyality): changes according real endpoint

- index.html
- src/es/components/controllers/checkout/Checkout.js
- src/es/components/pages/bugs/Konfiguration.html
Fixes bug when a "lehrmittel" is changed it reset the state of the insurance in the price calculation. Should now work
> fix: mit versicherung konfiguration

- src/es/components/controllers/withFacet/WithFacet.js
- src/es/components/molecules/filterCategories/FilterCategories.js
- src/es/components/molecules/filterSelect/FilterSelect.js
- src/es/components/molecules/navLevelItem/NavLevelItem.js
- src/es/components/pages/Angebotsliste-Suchergebnis.html
refactor(WithFacet.js): add logging for event in WithFacet class
fix(WithFacet.js): correct property name 'SearchText' to 'searchText'
feat(WithFacet.js): add logic to deselect filterItem if parent filter is selected
feat(WithFacet.js): add getLastSelectedFilterItem method to recursively find and mark the last selected filter item
refactor(FilterCategories.js): add logic to store first tree item in the component
fix(NavLevelItem.js): add type attribute to target object in event dispatch
fix(Angebotsliste-Suchergebnis.html): update endpoint and endpoint-auto-complete URLs to point to the integration environment
> fix(WithFacet.js): improve sector filtering

- src/es/components/controllers/withFacet/WithFacet.js
- src/es/components/molecules/filterCategories/FilterCategories.js
refactor(WithFacet.js): refactor logic for handling 'center' filter key in WithFacet component
fix(FilterCategories.js): update filter-id attribute value to use "center" prefix instead of region.urlpara
> feat(WithFacet.js, FilterCategories.js): improve center filter urls to 'center-' incl. center-id

- src/es/components/controllers/withFacet/WithFacet.js
refactor(WithFacet.js): improve handling of search text and filters in WithFacet component
feat(WithFacet.js): add functionality to delete search text parameter from URL when value is empty
> refactor(WithFacet.js): improve handling of search text and filters in WithFacet component [MIDUWEB-1398]

- src/es/components/controllers/abonnements/Abonnements.js
- src/es/components/molecules/abonnements/Abonnements.js
- src/es/components/molecules/eventDetail/EventDetail.js
- src/es/components/pages/Abonnements.html
refactor(Abonnements.js): add support for fetching locations based on event details and response data
feat(Abonnements.js): handle request-locations event to fetch locations data using POST method
fix(Abonnements.js): add conditional check before rendering content and receiving data
fix(EventDetail.js): format ks-m-abonnements attributes for better readability
fix(Abonnements.html): add endpoint attribute to ks-m-abonnements component
> refactor(Abonnements.js): add requestLocationListener [MIDUWEB-1347]

- src/es/components/controllers/autoComplete/AutoComplete.js
- src/es/components/molecules/filterSelect/FilterSelect.js
- src/es/components/organisms/offersPage/OffersPage.js
New language variable
**_FilterButton.SearchInputLabel_**
(e.g. german: "Suche:")
> refactor(FilterSelect.js): improve filter ui [MIDUWEB-1339]

- src/es/components/molecules/tile/Tile.js
- src/es/components/molecules/tileFactory/TileFactory.js
feat(TileFactory.js): add centerid property to course data object
> fix(Tile.js): add centerid attribute to ks-m-buttons component

- src/es/customer-loyality/controllers/VotingController.js
- src/es/customer-loyality/organisms/form/Form.js
- fixes ticket [MIDUWEB-1593](https://jira.migros.net/browse/MIDUWEB-1593)
- when only one option is selected, fill preferred variant with selected option. (Caused Error 400 on API).
- dont submit if validation error.
- show error message from API below form.
> fix(customer-loyality): use picked option for preferred variant

- src/css/variablesCustom.css
- src/es/components/pages/FormRaumreservierung.html
feat(FormRaumreservierung.html): add date and time input fields with validation and error messages
style(FormRaumreservierung.html): add spacing-l-flex div before and after the button element
chore(web-components-toolbox): update subproject commit hash to 1cb2f88b
> style(css): add grid x padding bottom variable declaration in variablesCustom.css

- src/es/components/molecules/login/default-/default-.html
feat(login.html): add any-key-listener attribute to the <a-input> element
style(login.html): reformat the <a-icon-mdx> element for better readability
> feat(login.html): add any-key-listener attribute to the <a-input> element

- src/es/components/molecules/teaser/story-/story-.css
- src/es/components/pages/Teaser.html
feat(Teaser.html): add new teaser component for brand 'ibaw' with ibaw-turquoise color and custom content
> style(teaser.css): add clip-path and padding styles to teaser component for brand 'ibaw' [MIDUWEB-1501]

- src/es/customer-loyality/organisms/form/Form.js
- no validation error when option none is picked.
> fix(customer-loyality): allow none response

- src/es/components/molecules/checkoutBookedOffer/CheckoutBookedOffer.js
fix(CheckoutBookedOffer.js): remove unnecessary CSS rules for checkout-booked-offer__total and checkout-booked-offer__total-price
> style(CheckoutBookedOffer.js): add media query for specific viewport to handle spacing [MIDUWEB-1317]

- src/es/components/organisms/tileList/TileList.js
chore(css): update subproject commit references for web-components-toolbox-migros-design-experience and web-components-toolbox submodules
> refactor(TileList.js): update logic to display different placeholders based on data.sort value [MIDUWEB-1330]

- src/es/components/controllers/autoComplete/AutoComplete.js
- src/es/components/molecules/autoCompleteList/AutoCompleteList.js
- src/es/components/molecules/autoCompleteList/default-/default-.html
- src/es/components/organisms/offersPage/OffersPage.js
- src/es/components/pages/Angebotsliste-Suchergebnis.html
chore(css): update subproject commit reference in web-components-toolbox-migros-design-experience
chore(components): update subproject commit reference in web-components-toolbox
> feat(AutoComplete.js): add content search to autocomplete [MIDUWEB-1583]

- src/es/components/controllers/autoComplete/AutoComplete.js
- src/es/components/molecules/autoCompleteList/AutoCompleteList.js
refactor(AutoCompleteList): simplify input search value retrieval by using array mapping and optional chaining for better readability and maintainability
> fix(autoComplete): add check for empty string in token validation to prevent unnecessary requests

- src/es/components/molecules/buttons/Buttons.js
https://jira.migros.net/browse/MIDUWEB-1725
> positioning wishlist heart button

- src/es/components/controllers/withFacet/WithFacet.js
chore: update submodule references for web-components-toolbox and migros-design-experience to latest commits
> fix(WithFacet.js): set filterItem.skipCountUpdate to false to prevent unintended behavior during filtering process [MIDUWEB-1799]

- src/es/components/molecules/tileFactory/TileFactory.js
Jira Ticket
https://jira.migros.net/browse/MIDUWEB-1765
> fix(TileFactory.js): improve parsing of title/bezeichnung [MIDUWEB-1765]
